config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :restaurants
  get 'nukem_all' => 'restaurants#nukem_all'
  post 'pick' => 'home#index'

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  validates :name, presence: true, length: { maximum: 30 }
  validates :cuisine, length: { maximum: 30 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  # Want to authenticate whole site so I put it here instead of on any given page
  http_basic_authenticate_with name: "me", password: "pw"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    init
    render_msg
  end

  private

  # Gathers all data needed for picking a restaurant, including filters
  def init
    # grab only the attributes that exist to populate the filters
    @cuisines = Restaurant.select(:cuisine).distinct.map(&:cuisine) # {|r| r.cuisine } == (&:cuisine)
    @distances = Restaurant.select(:distance).distinct.map(&:distance) # {|r| r.cuisine } == (&:cuisine)
    @costs = Restaurant.select(:cost).distinct.map(&:cost) # {|r| r.cuisine } == (&:cuisine)

    @selected_cuisine = params[:cuisine] if params[:cuisine]
    @selected_distance = params[:distance] if params[:distance]
    @selected_cost = params[:cost] if params[:cost]

    # gets all the restaurants
    @restaurants = Restaurant.all
  end

  # Renders the restaurant picking
  def render_msg
    @msg = ''
    if @restaurants.count == 0
      @error_msg = "You haven't created any restaurants yet!"
    else
      if params[:cuisine].present?
        filter
      else
        @error_msg = "You haven't picked any restaurants yet!"
      end
    end
  end

  def filter
    filter_parameters = gather_filters

    query_with_filters(filter_parameters)

    pick_restaurant
  end

  def pick_restaurant
    if @filtered.empty?
      @restaurant = Restaurant.offset(rand(Restaurant.count)).first
      @msg = "None matched, but I picked another for you at random: #{@restaurant.name}"
    else
      @msg = @filtered.sample.name
    end
  end

  def query_with_filters(filter_parameters)
    @filtered = Restaurant.where(filter_parameters)
  end

  def gather_filters
    filter_parameters = {}
    [:cuisine, :cost, :distance].each do |filter|
      filter_parameters[filter] = params[filter] if params[filter] != 'Any'
    end

    # filter_parameters[:cuisine] = params[:cuisine] if params[:cuisine] != 'Any'
    # filter_parameters[:cost] = params[:cost] if params[:cost] != 'Any'
    # filter_parameters[:distance] = params[:distance] if params[:distance] != 'Any'

    filter_parameters
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_filter :check_for_cancel, :only => [:create, :update]
  before_filter :cuisine_options
  #Lists all Restaurants on the Manage Restaurants page
  def index
    @restaurants = Restaurant.all
  end

  # Shows the current restaurant
  def show
    @restaurant = Restaurant.find(params[:id])
  end

  # Displays the new restaurant form page and initializes a default restaurant instance to avoid nil references
  # to the variable (avoid errors specifically in the validation logic in adding new restaurants)
  def new
    @restaurant = Restaurant.new
  end

  # Gives you the id for the restaurant you want to edit. Helps you get to that page.
  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  # Updates restaurant
  def update
    @restaurant = Restaurant.find(params[:id])

    respond_to do |format|
      if @restaurant.update(restaurant_params)
        flash[:success] = 'Restaurant successfully updated!'
        format.html { redirect_to restaurants_path}
        format.json { render :show, status: :ok, location: restaurants_path }
      else
        flash[:danger] = "Error(s) updating restaurant: #{@restaurant.errors.full_messages}"
        format.html { render :edit }
        format.json { render json: @restaurants.errors, status: :unprocessable_entity }
      end
    end
  end

  # Handles Saving a new restaurant. Redirects the page to the restaurant's show page
  def create
    @restaurant = Restaurant.new(restaurant_params)
    respond_to do |format|
      if @restaurant.save
        flash[:success] = 'Restaurant successfully created!'
        format.html { redirect_to restaurants_path}
        format.json { render :show, status: :created, location: restaurants_path }
      else
        flash[:danger] = "Error(s) creating restaurant: #{@restaurant.errors.full_messages}"
        format.html { render :new }
        format.json { render json: @restaurants.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])

    if @restaurant.destroy
      respond_to do |format|
        flash[:success] = 'Restaurant successfully removed!'
        format.html { redirect_to restaurants_path }
      end
    else
      flash[:danger] = "Error(s) removing restaurant: #{@restaurant.errors.full_messages}"
      format.html { redirect_to restaurants_path }
    end
  end

  #TODO implement an "are you sure" dialog, this is something rails has built in. Find it!
  def nukem_all
    Restaurant.destroy_all
    redirect_to restaurants_path
  end

  # Checks for canceling a creation or update to a form
  def check_for_cancel
    if(params.key?("cancel"))
      redirect_to restaurants_path
    end
  end

  def add_cuisine_types(posted_type)
    @cuisine_types << posted_type
  end

  private

  # Strong Params. We could just grab them all with params[:restaurant] but that would
  # open it up to malicious acts. So, we make sure only to grab the ones that matter, in
  # this case, :name
  # Making it private further encapsulates and protects the method from outside influence
  def restaurant_params
    params.require(:restaurant).permit(:name, :distance, :cuisine, :cost)
  end

  def cuisine_options
    @cuisine_types = ["Mexican","Italian","American","Japanese","Chinese"]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pick_decorator.rb
# Used to handle logic to show someone's pick depending on if a restaurant exists or not
class PickDecorator
  def initialize(restaurant, count)
    @restaurant = restaurant
    @count = count
  end

  def message
    if @restaurant.nil?
      "no restaurants available"
    else
      "#{@restaurant.name} picked from #{@count} possibilities"
    end
  end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/home/_form.html.erb
<%= form_tag(pick_path, :method => "post") do %>
  <div>
    <table>
      <tr>
        <%= label_tag(:cuisine_fltr, "Cuisine:") %>
        <select name="cuisine" id="cuisine_fltr">
          <option>Any</option>
          <% @cuisines.each do |c| %>
              <% if c == @selected_cuisine %>
                <option selected="selected"><%=c%></option>
              <% else %>
                <option><%=c%></option>
              <% end %>
          <% end %>
        </select>
      </tr>
      <tr>
        <%= label_tag(:distance_fltr, "Distance:") %>
        <select name="distance" id="distance_fltr">
          <option>Any</option>
          <% @distances.each do |c| %>
              <% if c == @selected_distance %>
                  <option selected="selected"><%=c%></option>
              <% else %>
                  <option><%=c%></option>
              <% end %>
          <% end %>
        </select>
      </tr>
      <tr>
        <%= label_tag(:cost_fltr, "Cost:") %>
        <select name="cost" id="cost_fltr">
          <option>Any</option>
          <% @costs.each do |c| %>
              <% if c == @selected_cost %>
                  <option selected="selected"><%=c%></option>
              <% else %>
                  <option><%=c%></option>
              <% end %>
          <% end %>
        </select>
      </tr>
    </table>
  </div>
  <div>
    <%= button_tag(type: "submit", class: "btn-lg btn btn-success") do %>
        <i class="glyphicon glyphicon-cutlery"></i> Pick For Me!
    <% end %>
  </div>
<% end %>

app/views/home/index.html.erb
<div class="jumbotron">
  <h1>Chewser</h1>
  <p class="lead">Welcome to Chewser! Let me tell you where you're going to eat, since you're too indecisive.</p>
  <hr>
  <div class="text-center">
    Filters:
    <%= render 'form' %>
  </div>
  <hr>
  <% if !@msg.empty?%>
  <div class="text-center">
    <p class="lead">You will be dining with the fine people at:</p>
    <div>
      <p><%= @msg %></p>
    </div>
  </div>
  <% else %>
      <div class="text-center">
          <p class="lead"><%= @error_msg %></p>
      </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Chewser</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'shared/navigation' %>

  <div id="main-container" class="container-fluid">
    <div class="row">
      <div class="col-xs-12">
        <% flash.each do |name, msg| -%>
            <%= content_tag :div, msg, class: "alert alert-#{name}" %>
        <% end -%>
      </div>
    </div>

    <%= yield %>

    <div class="footer">
      <p>&copy; Steven Shepherd 2016</p>
    </div>
  </div> <!-- /container -->
</body>
</html>

app/views/restaurants/_form.html.erb
<!-- partial 'template' for my forms -->
<%= form_for @restaurant do |f| %>
    <% if @restaurant.errors.any? %>
        <div id="error_explanation">
          <h3>
            <%= pluralize(@restaurant.errors.count, "error") %> prohibited
            this restaurant from being saved:
          </h3>
          <ul>
            <% @restaurant.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <p>
      <%= f.label 'Name:'%>
      <%= f.text_field :name%>
    </p>

    <p>
      <%= f.label 'Distance:' %>
      <%= f.select :distance, [['0-2 miles'], ['2-5 miles'], ['5+ miles']] %>
    </p>

    <p>
      <%= f.label 'Cuisine:' %>
      <%= f.text_field :cuisine%>
    </p>
    <p>
      <%= f.label 'Cost:' %>
      <%= f.select :cost, [['$'], ['$$'], ['$$$']] %>
    </p>
    <p>
      <%= f.submit :class => 'btn btn-primary' %>
      <%= f.submit 'clear', :type => 'reset', :class => 'btn btn-default' %>
      <%= button_tag 'Cancel', :type => 'cancel', :name => 'cancel', :class => 'btn btn-default' %>
    </p>
<% end %>

app/views/restaurants/edit.html.erb
<div class="jumbotron">
  <h1 class="text-center">Chewser</h1>
  <hr>
  <h2 class="text-center"> Edit Restaurant </h2>
  <hr>
  <%= render 'form' %>
</div>

app/views/restaurants/index.html.erb
<!-- TODO: Figure out how to clear a name field when you first edit a restaurant that already had a name -->
<div class="jumbotron">
  <h1>Chewser</h1>
  <h2>Manage Restaurants</h2>
  <p class="lead">Here you can manage your current pool of restaurants. </p>

  <table class="table-condensed">
    <tr>
      <th>Restaurant</th>
      <th>Distance</th>
      <th>Cuisine</th>
      <th>Cost</th>
    </tr>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= restaurant.name%></td>
        <td><%= restaurant.distance%></td>
        <td><%= restaurant.cuisine%></td>
        <td><%= restaurant.cost%></td>
        <td><%= link_to 'Edit', edit_restaurant_path(restaurant),class:'btn btn-info btn-xs'%></td>
        <td><%= link_to 'Remove', restaurant_path(restaurant),
                        method: :delete,
                        data: { confirm: 'Are you sure you want to delete this restaurant?' },
                        class: 'btn btn-danger btn-xs'%></td>
      </tr>
    <% end %>
  </table>
  <hr>
<!-- resources create CRUD routes, but this is a custom method, and I needed to create a route in
config/routes.rb for destroy all-->
  <p>
  <%= link_to new_restaurant_path, class: 'btn btn-success' do %>
      <i class="glyphicon glyphicon-plus"></i> Add
  <% end %>

  <%= link_to 'Clear List', nukem_all_path,
                data: { confirm: 'Are you sure you want to delete EVERYTHING?' },
                class: 'btn btn-danger'%></p>
</div>

app/views/restaurants/new.html.erb
<div class="jumbotron">
  <h1>Chewser</h1>
  <h2>New Restaurant</h2>
  <p class="lead">Please fill in the details</p>
  <hr>
  <%= render 'form' %>
</div>

app/views/restaurants/show.html.erb
<div class="jumbotron">
  <h1 class="text-center">Chewser</h1>
  <hr>
  <p class="text-center">
    <strong>Restaurant:</strong>
    <%= @restaurant.name %>
  </p>
  <p class="text-center">
    <strong>Distance:</strong>
    <%= @restaurant.distance%>
  </p>
  <p class="text-center">
    <strong>Cuisine:</strong>
    <%= @restaurant.cuisine%>
  </p>
  <p class="text-center">
    <strong>Cost:</strong>
    <%= @restaurant.cost%>
  </p>
  <div class="text-center">
    <%= link_to 'Edit', edit_restaurant_path(@restaurant),class:'btn btn-info'%>
    <%=link_to 'Remove', restaurant_path(@restaurant),
            method: :delete,
            data: { confirm: 'Are you sure you want to delete this restaurant?' },
            class: 'btn btn-danger'%>
  </div>
</div>

app/views/shared/_navigation.html.erb
<!-- A cool alternate nav class is navbar navbar-inverse navbar-fixed-top-->
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <%= link_to 'Home', root_path, class: "navbar-brand" %>
      <%= link_to 'Manage', restaurants_path, class: "navbar-brand" %>
    </div>
  </div>
</nav>